scrape_configs:
  - job_name: 'statistics api'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['192.168.50.17:8080']
otlp:  
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - deployment.environment
    - k8s.namespace.name
    - k8s.pod.name
