[security]
jwtSecret = "./test_config/public_key.pem"
jwtAlgorithm = "RS256"

[server]
workers = 50
httpPort = 8080

[database.dbType.postgresql]
connectionString = ""
maxConnections = 50
minConnections = 50
acquireTimeout = 6000
acquireSlowThreshold = 3000
idleTimeout = 3000
maxLifetime = 36000