[logging]
target = true
thread_ids = false
thread_names = true
line_number = false
level = true
ansi = true
file = "./logs/app.log"
directives = ["sqlx::query=info",]

[security]
jwtSecret = "./test_config/public_key.pem"
jwtAlgorithm = "RS256"

[server]
workers = 50
httpPort = 8080

[database.dbType.postgresql]
connectionString = "postgres://statistics_rw:statistics@greyhawk.forgottendonkey.com:5432/statistics"
maxConnections = 50
minConnections = 50
acquireTimeout = 6000
acquireSlowThreshold = 3000
idleTimeout = 3000
maxLifetime = 36000
