[logging]
target = true
thread_ids = true
thread_names = false
line_number = false
level = true
ansi = false
file = false
logfile = "./logs/app.log"
directives = ["sqlx::query=debug",]

[security]
incomingVerificationRequirements = [
    "CheckExpired", 
    { DerivedRequired = { name = "@method" } }, 
    { HeaderRequired = { name = "x-request-id" } }, 
    "CreatedRequired", 
    { HeaderRequired = { name = "x-fd-userid" } }, 
    "ExpiresRequired", 
]
responseGenerationRequirements = [
    { DerivedRequired = { name = "@status" } },
    { HeaderRequiredIfIncluded = { name = "x-request-id" } },
    { HeaderRequiredIfBodyPresent = { name = "content-type" } },
    { HeaderRequiredIfBodyPresent = { name = "content-digest" } },
    { GenerateExpires = { expires_secs = 300 } },
    "GenerateCreated",
]
[security.generatingSecret]
privateKey = { path = "./test_config/keys/private_key1.pem", algorithm = "rsa-pss-sha512", keyId = "123456789" }

[[security.verificationSecrets]]
[security.verificationSecrets.publicKeyFile]
path = "./test_config/keys/public_key1.pem"
algorithm = "rsa-pss-sha512"
keyId = "key1"

[[security.verificationSecrets]]
[security.verificationSecrets.publicKeyFile]
path = "./test_config/keys/public_key2.pem"
algorithm = "rsa-pss-sha512"
keyId = "key2"

[[security.verificationSecrets]]
[security.verificationSecrets.sharedSecret]
secret = "test"
algorithm = "hmac-sha256"
keyId = "key3"

[[security.verificationSecrets]]
[security.verificationSecrets.publicKeyFile]
path = "./test_config/keys/public_key4.pem"
algorithm = "ecdsa-p256-sha256"
keyId = "key4"

[[security.verificationSecrets]]
[security.verificationSecrets.publicKeyFile]
path = "./test_config/keys/public_key5.pem"
algorithm = "ecdsa-p384-sha384"
keyId = "key5"

[[security.verificationSecrets]]
[security.verificationSecrets.publicKeyFile]
path = "./test_config/keys/public_key6.pem"
algorithm = "ed25519"
keyId = "key6"

[server]
workers = 50
httpPort = 8080

[database.dbType.postgresql]
connectionString = ""
maxConnections = 10
minConnections = 5
acquireTimeout = 6000
acquireSlowThreshold = 3000
idleTimeout = 3000
maxLifetime = 36000


