[logging]
target = true
thread_ids = true
thread_names = false
line_number = false
level = true
ansi = false
file = false
logfile = "./logs/app.log"
directives = ["sqlx::query=debug",]

[security]
incomingVerificationRequirements = [
    "CheckExpired", 
    { DerivedRequired = { name = "@method" } }, 
    { HeaderRequired = { name = "x-request-id" } }, 
    "CreatedRequired", 
    { HeaderRequired = { name = "x-fd-userid" } }, 
    "ExpiresRequired", 
]
responseGenerationRequirements = [
    { DerivedRequired = { name = "@status" } },
    { HeaderRequiredIfIncluded = { name = "x-request-id" } },
    { HeaderRequiredIfBodyPresent = { name = "content-type" } },
    { HeaderRequiredIfBodyPresent = { name = "content-digest" } },
    { GenerateExpires = { expires_secs = 300 } },
    "GenerateCreated",
]
[security.generatingSecret]
privateKey = { path = "./test_config/keys/private_key1.pem", algorithm = "rsa-pss-sha512" }

[security.verificationSecrets.key1.publicKeyFile]
path = "./test_config/keys/public_key1.pem"
algorithm = "rsa-pss-sha512"

[security.verificationSecrets.key2.publicKeyFile]
path = "./test_config/keys/public_key2.pem"
algorithm = "rsa-pss-sha512"

[security.verificationSecrets.key3.sharedSecret]
secret = "test"
algorithm = "hmac-sha256"

[security.verificationSecrets.key4.publicKeyFile]
path = "./test_config/keys/public_key4.pem"
algorithm = "ecdsa-p256-sha256"

[security.verificationSecrets.key5.publicKeyFile]
path = "./test_config/keys/public_key5.pem"
algorithm = "ecdsa-p384-sha384"

[security.verificationSecrets.key6.publicKeyFile]
path = "./test_config/keys/public_key6.pem"
algorithm = "ed25519"

[server]
workers = 50
httpPort = 8080

[database.dbType.postgresql]
connectionString = "postgres://postgres:1234@localhost:5432/statistics"
maxConnections = 50
minConnections = 5
acquireTimeout = 6000
acquireSlowThreshold = 3000
idleTimeout = 3000
maxLifetime = 36000


