[security]
jwtSecret = "./test_config/public_key.pem"
jwtAlgorithm = "RS256"

[server]
workers = 50
httpPort = 8080

[database.dbType.postgresql]
connectionString = "postgres://statistics_rw:statistics@greyhawk.forgottendonkey.com:5432/statistics"
maxConnections = 50
minConnections = 50
acquireTimeout = 3000
acquireSlowThreshold = 1000
idleTimeout = 3000
maxLifetime = 36000