services:
  jaeger:
    image: jaegertracing/jaeger:latest
    depends_on:
      - prometheus
    restart: always
    ports:
      - "4318:4318"
      - "4317:4317"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5775:5775/udp"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - '9090:9090'
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.enable-otlp-receiver
